version: "3.8"

services:
  db:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      postgres_user: postgres
      postgres_password: LMSDB
      postgres_db: LMS_DB
    ports:
      - "5432:5432"